export const AUTH_BEGIN_LOGIN = 'AUTH_BEGIN_LOGIN';
export const AUTH_FORM_CLEAN = 'AUTH_FORM_CLEAN';
export const AUTH_FORM_ERRORS = 'AUTH_FORM_ERRORS';
export const AUTH_FORM_NON_FIELD_ERROR = 'AUTH_FORM_NON_FIELD_ERROR';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_PERMISSIONS = 'AUTH_PERMISSIONS';
export const AUTH_PROFILE = 'AUTH_PROFILE';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const ACCOUNT_ACCOUNT_CHOICE_COMMENT_ORDER = 'ACCOUNT_ACCOUNT_CHOICE_COMMENT_ORDER';
export const ACCOUNT_ACCOUNT_CHOICE_TIME_FORMAT = 'ACCOUNT_ACCOUNT_CHOICE_TIME_FORMAT';
export const ACCOUNT_ACCOUNT_CHOICE_TIME_ZONE = 'ACCOUNT_ACCOUNT_CHOICE_TIME_ZONE';
export const ACCOUNT_ACCOUNT_FORM_CLEAN = 'ACCOUNT_ACCOUNT_FORM_CLEAN';
export const ACCOUNT_ACCOUNT_FORM_DATA = 'ACCOUNT_ACCOUNT_FORM_DATA';
export const ACCOUNT_ACCOUNT_FORM_ERRORS = 'ACCOUNT_ACCOUNT_FORM_ERRORS';
export const ACCOUNT_ACCOUNT_FORM_SUCCESS = 'ACCOUNT_ACCOUNT_FORM_SUCCESS';
export const ACCOUNT_ACCOUNT_FORM_VALIDATION = 'ACCOUNT_ACCOUNT_FORM_VALIDATION';
export const ACCOUNT_ACCOUNT_SEARCH = 'ACCOUNT_ACCOUNT_SEARCH';

export const ACCOUNT_LOGIN_DELETE = 'ACCOUNT_LOGIN_DELETE';
export const ACCOUNT_LOGIN_FORM_CLEAN = 'ACCOUNT_LOGIN_FORM_CLEAN';
export const ACCOUNT_LOGIN_FORM_DATA = 'ACCOUNT_LOGIN_FORM_DATA';
export const ACCOUNT_LOGIN_FORM_ERRORS = 'ACCOUNT_LOGIN_FORM_ERRORS';
export const ACCOUNT_LOGIN_FORM_SUCCESS = 'ACCOUNT_LOGIN_FORM_SUCCESS';
export const ACCOUNT_LOGIN_FORM_VALIDATION = 'ACCOUNT_LOGIN_FORM_VALIDATION';
export const ACCOUNT_LOGIN_PERMISSION_BASE = 'ACCOUNT_LOGIN_PERMISSION_BASE';
export const ACCOUNT_LOGIN_PERMISSION_USER = 'ACCOUNT_LOGIN_PERMISSION_USER';

export const BILLING_PAYMENT_CHOICE_COMPANY = 'BILLING_PAYMENT_CHOICE_COMPANY';
export const BILLING_PAYMENT_CHOICE_MERCHANT = 'BILLING_PAYMENT_CHOICE_MERCHANT';
export const BILLING_PAYMENT_CHOICE_METHOD = 'BILLING_PAYMENT_CHOICE_METHOD';
export const BILLING_PAYMENT_DELETE = 'BILLING_PAYMENT_DELETE';
export const BILLING_PAYMENT_FORM_CLEAN = 'BILLING_PAYMENT_FORM_CLEAN';
export const BILLING_PAYMENT_FORM_DATA = 'BILLING_PAYMENT_FORM_DATA';
export const BILLING_PAYMENT_FORM_ERRORS = 'BILLING_PAYMENT_FORM_ERRORS';
export const BILLING_PAYMENT_FORM_NON_FIELD_ERROR = 'BILLING_PAYMENT_FORM_NON_FIELD_ERROR';
export const BILLING_PAYMENT_FORM_SUCCESS = 'BILLING_PAYMENT_FORM_SUCCESS';
export const BILLING_PAYMENT_FORM_VALIDATION = 'BILLING_PAYMENT_FORM_VALIDATION';
export const BILLING_PAYMENT_SEARCH = 'BILLING_PAYMENT_SEARCH';

export const BILLING_REASON_CHOICE_TYPE = 'BILLING_REASON_CHOICE_TYPE';
export const BILLING_REASON_DELETE = 'BILLING_REASON_DELETE';
export const BILLING_REASON_FORM_CLEAN = 'BILLING_REASON_FORM_CLEAN';
export const BILLING_REASON_FORM_DATA = 'BILLING_REASON_FORM_DATA';
export const BILLING_REASON_FORM_ERRORS = 'BILLING_REASON_FORM_ERRORS';
export const BILLING_REASON_FORM_SUCCESS = 'BILLING_REASON_FORM_SUCCESS';
export const BILLING_REASON_FORM_VALIDATION = 'BILLING_REASON_FORM_VALIDATION';
export const BILLING_REASON_SEARCH = 'BILLING_REASON_SEARCH';

export const COMPANY_COMPANY_DELETE = 'COMPANY_COMPANY_DELETE';
export const COMPANY_COMPANY_FORM_CLEAN = 'COMPANY_COMPANY_FORM_CLEAN';
export const COMPANY_COMPANY_FORM_DATA = 'COMPANY_COMPANY_FORM_DATA';
export const COMPANY_COMPANY_FORM_ERRORS = 'COMPANY_COMPANY_FORM_ERRORS';
export const COMPANY_COMPANY_FORM_SUCCESS = 'COMPANY_COMPANY_FORM_SUCCESS';
export const COMPANY_COMPANY_FORM_VALIDATION = 'COMPANY_COMPANY_FORM_VALIDATION';
export const COMPANY_COMPANY_SEARCH = 'COMPANY_COMPANY_SEARCH';

export const COMPANY_DNS_CHOICE_NS = 'COMPANY_DNS_CHOICE_NS';
export const COMPANY_DNS_CHOICE_RECORD_TYPE = 'COMPANY_DNS_CHOICE_RECORD_TYPE';
export const COMPANY_DNS_DELETE = 'COMPANY_DNS_DELETE';
export const COMPANY_DNS_FORM_CLEAN = 'COMPANY_DNS_FORM_CLEAN';
export const COMPANY_DNS_FORM_DATA = 'COMPANY_DNS_FORM_DATA';
export const COMPANY_DNS_FORM_ERRORS = 'COMPANY_DNS_FORM_ERRORS';
export const COMPANY_DNS_FORM_SUCCESS = 'COMPANY_DNS_FORM_SUCCESS';
export const COMPANY_DNS_FORM_VALIDATION = 'COMPANY_DNS_FORM_VALIDATION';
export const COMPANY_DNS_NAMESERVER_BASE = 'COMPANY_DNS_NAMESERVER_BASE';
export const COMPANY_DNS_NAMESERVER_DOMAIN = 'COMPANY_DNS_NAMESERVER_DOMAIN';
export const COMPANY_DNS_SEARCH = 'COMPANY_DNS_SEARCH';

export const COMPANY_DOMAIN_CHOICE_COMPANY = 'COMPANY_DOMAIN_CHOICE_COMPANY';
export const COMPANY_DOMAIN_DELETE = 'COMPANY_DOMAIN_DELETE';
export const COMPANY_DOMAIN_FORM_CLEAN = 'COMPANY_DOMAIN_FORM_CLEAN';
export const COMPANY_DOMAIN_FORM_DATA = 'COMPANY_DOMAIN_FORM_DATA';
export const COMPANY_DOMAIN_FORM_ERRORS = 'COMPANY_DOMAIN_FORM_ERRORS';
export const COMPANY_DOMAIN_FORM_SUCCESS = 'COMPANY_DOMAIN_FORM_SUCCESS';
export const COMPANY_DOMAIN_FORM_VALIDATION = 'COMPANY_DOMAIN_FORM_VALIDATION';
export const COMPANY_DOMAIN_SEARCH = 'COMPANY_DOMAIN_SEARCH';

export const HARDWARE_CLIENT_CHOICE_DOMAIN = 'HARDWARE_CLIENT_CHOICE_DOMAIN';
export const HARDWARE_CLIENT_CHOICE_HARDWARE = 'HARDWARE_CLIENT_CHOICE_HARDWARE';
export const HARDWARE_CLIENT_CHOICE_TARGET = 'HARDWARE_CLIENT_CHOICE_TARGET';
export const HARDWARE_CLIENT_CHOICE_WEB = 'HARDWARE_CLIENT_CHOICE_WEB';
export const HARDWARE_CLIENT_DELETE = 'HARDWARE_CLIENT_DELETE';
export const HARDWARE_CLIENT_FORM_CLEAN = 'HARDWARE_CLIENT_FORM_CLEAN';
export const HARDWARE_CLIENT_FORM_DATA = 'HARDWARE_CLIENT_FORM_DATA';
export const HARDWARE_CLIENT_FORM_ERRORS = 'HARDWARE_CLIENT_FORM_ERRORS';
export const HARDWARE_CLIENT_FORM_SUCCESS = 'HARDWARE_CLIENT_FORM_SUCCESS';
export const HARDWARE_CLIENT_FORM_VALIDATION = 'HARDWARE_CLIENT_FORM_VALIDATION';
export const HARDWARE_CLIENT_INSTALL_SUCCESS = 'HARDWARE_CLIENT_INSTALL_SUCCESS';
export const HARDWARE_CLIENT_INSTALL_VALIDATION = 'HARDWARE_CLIENT_INSTALL_VALIDATION';
export const HARDWARE_CLIENT_INSTALL_WARNING = 'HARDWARE_CLIENT_INSTALL_WARNING';
export const HARDWARE_CLIENT_SEARCH = 'HARDWARE_CLIENT_SEARCH';

export const HARDWARE_COMPANY_CHOICE_DOMAIN = 'HARDWARE_COMPANY_CHOICE_DOMAIN';
export const HARDWARE_COMPANY_CHOICE_TARGET = 'HARDWARE_COMPANY_CHOICE_TARGET';
export const HARDWARE_COMPANY_DELETE = 'HARDWARE_COMPANY_DELETE';
export const HARDWARE_COMPANY_FORM_CLEAN = 'HARDWARE_COMPANY_FORM_CLEAN';
export const HARDWARE_COMPANY_FORM_DATA = 'HARDWARE_COMPANY_FORM_DATA';
export const HARDWARE_COMPANY_FORM_ERRORS = 'HARDWARE_COMPANY_FORM_ERRORS';
export const HARDWARE_COMPANY_FORM_SUCCESS = 'HARDWARE_COMPANY_FORM_SUCCESS';
export const HARDWARE_COMPANY_FORM_VALIDATION = 'HARDWARE_COMPANY_FORM_VALIDATION';
export const HARDWARE_COMPANY_INSTALL_SUCCESS = 'HARDWARE_COMPANY_INSTALL_SUCCESS';
export const HARDWARE_COMPANY_INSTALL_VALIDATION = 'HARDWARE_COMPANY_INSTALL_VALIDATION';
export const HARDWARE_COMPANY_INSTALL_WARNING = 'HARDWARE_COMPANY_INSTALL_WARNING';
export const HARDWARE_COMPANY_SEARCH = 'HARDWARE_COMPANY_SEARCH';

export const NETWORK_POOL_CHOICE_ASSIGNED = 'NETWORK_POOL_CHOICE_ASSIGNED';
export const NETWORK_POOL_DELETE = 'NETWORK_POOL_DELETE';
export const NETWORK_POOL_FORM_CLEAN = 'NETWORK_POOL_FORM_CLEAN';
export const NETWORK_POOL_FORM_DATA = 'NETWORK_POOL_FORM_DATA';
export const NETWORK_POOL_FORM_ERRORS = 'NETWORK_POOL_FORM_ERRORS';
export const NETWORK_POOL_FORM_SUCCESS = 'NETWORK_POOL_FORM_SUCCESS';
export const NETWORK_POOL_FORM_VALIDATION = 'NETWORK_POOL_FORM_VALIDATION';
export const NETWORK_POOL_SEARCH = 'NETWORK_POOL_SEARCH';
export const NETWORK_POOL_TYPES = 'NETWORK_POOL_TYPES';

export const SETTING_BANNED_CHOICE_TYPE = 'SETTING_BANNED_CHOICE_TYPE';
export const SETTING_BANNED_DELETE = 'SETTING_BANNED_DELETE';
export const SETTING_BANNED_FORM_CLEAN = 'SETTING_BANNED_FORM_CLEAN';
export const SETTING_BANNED_FORM_DATA = 'SETTING_BANNED_FORM_DATA';
export const SETTING_BANNED_FORM_ERRORS = 'SETTING_BANNED_FORM_ERRORS';
export const SETTING_BANNED_FORM_SUCCESS = 'SETTING_BANNED_FORM_SUCCESS';
export const SETTING_BANNED_FORM_VALIDATION = 'SETTING_BANNED_FORM_VALIDATION';
export const SETTING_BANNED_SEARCH = 'SETTING_BANNED_SEARCH';

export const SETTING_EMAIL_CHOICE_TEMPLATE = 'SETTING_EMAIL_CHOICE_TEMPLATE';
export const SETTING_EMAIL_DELETE = 'SETTING_EMAIL_DELETE';
export const SETTING_EMAIL_FORM_CLEAN = 'SETTING_EMAIL_FORM_CLEAN';
export const SETTING_EMAIL_FORM_DATA = 'SETTING_EMAIL_FORM_DATA';
export const SETTING_EMAIL_FORM_ERRORS = 'SETTING_EMAIL_FORM_ERRORS';
export const SETTING_EMAIL_FORM_SUCCESS = 'SETTING_EMAIL_FORM_SUCCESS';
export const SETTING_EMAIL_FORM_VALIDATION = 'SETTING_EMAIL_FORM_VALIDATION';
export const SETTING_EMAIL_SEARCH = 'SETTING_EMAIL_SEARCH';

export const STORE_FRAUD_CHOICE_TYPE = 'STORE_FRAUD_CHOICE_TYPE';
export const STORE_FRAUD_DELETE = 'STORE_FRAUD_DELETE';
export const STORE_FRAUD_FORM_CLEAN = 'STORE_FRAUD_FORM_CLEAN';
export const STORE_FRAUD_FORM_DATA = 'STORE_FRAUD_FORM_DATA';
export const STORE_FRAUD_FORM_ERRORS = 'STORE_FRAUD_FORM_ERRORS';
export const STORE_FRAUD_FORM_SUCCESS = 'STORE_FRAUD_FORM_SUCCESS';
export const STORE_FRAUD_FORM_VALIDATION = 'STORE_FRAUD_FORM_VALIDATION';
export const STORE_FRAUD_SEARCH = 'STORE_FRAUD_SEARCH';

export const STORE_PRODUCT_CHOICE_COMPANY = 'STORE_PRODUCT_CHOICE_COMPANY';
export const STORE_PRODUCT_CHOICE_IP = 'STORE_PRODUCT_CHOICE_IP';
export const STORE_PRODUCT_CHOICE_WEB = 'STORE_PRODUCT_CHOICE_WEB';

export const STORE_PRODUCT_DOMAIN_DELETE = 'STORE_PRODUCT_DOMAIN_DELETE';
export const STORE_PRODUCT_DOMAIN_FORM_CLEAN = 'STORE_PRODUCT_DOMAIN_FORM_CLEAN';
export const STORE_PRODUCT_DOMAIN_FORM_DATA = 'STORE_PRODUCT_DOMAIN_FORM_DATA';
export const STORE_PRODUCT_DOMAIN_FORM_ERRORS = 'STORE_PRODUCT_DOMAIN_FORM_ERRORS';
export const STORE_PRODUCT_DOMAIN_FORM_SUCCESS = 'STORE_PRODUCT_DOMAIN_FORM_SUCCESS';
export const STORE_PRODUCT_DOMAIN_FORM_VALIDATION = 'STORE_PRODUCT_DOMAIN_FORM_VALIDATION';
export const STORE_PRODUCT_DOMAIN_SEARCH = 'STORE_PRODUCT_DOMAIN_SEARCH';

export const STORE_PRODUCT_PRICE_DELETE = 'STORE_PRODUCT_PRICE_DELETE';
export const STORE_PRODUCT_PRICE_FORM_CLEAN = 'STORE_PRODUCT_PRICE_FORM_CLEAN';
export const STORE_PRODUCT_PRICE_FORM_DATA = 'STORE_PRODUCT_PRICE_FORM_DATA';
export const STORE_PRODUCT_PRICE_FORM_ERRORS = 'STORE_PRODUCT_PRICE_FORM_ERRORS';
export const STORE_PRODUCT_PRICE_FORM_SUCCESS = 'STORE_PRODUCT_PRICE_FORM_SUCCESS';
export const STORE_PRODUCT_PRICE_FORM_VALIDATION = 'STORE_PRODUCT_PRICE_FORM_VALIDATION';
export const STORE_PRODUCT_PRICE_SEARCH = 'STORE_PRODUCT_PRICE_SEARCH';