export const AUTH_PERMISSIONS = 'AUTH_PERMISSIONS';
export const AUTH_PROFILE = 'AUTH_PROFILE';
export const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const COMPANY_DNS_NAMESERVER_BASE = 'COMPANY_DNS_NAMESERVER_BASE';
export const COMPANY_DNS_NAMESERVER_DOMAIN = 'COMPANY_DNS_NAMESERVER_DOMAIN';

export const EMPLOYEE_MANAGE_PERMISSION_BASE = 'EMPLOYEE_MANAGE_PERMISSION_BASE';
export const EMPLOYEE_MANAGE_PERMISSION_USER = 'EMPLOYEE_MANAGE_PERMISSION_USER';

export const FORM_ARRAY = 'FORM_ARRAY';
export const FORM_CHOICES = 'FORM_CHOICES';
export const FORM_CLEAN = 'FORM_CLEAN';
export const FORM_DELETE = 'FORM_DELETE';
export const FORM_ERRORS = 'FORM_ERRORS';
export const FORM_NON_FIELD_ERROR = 'FORM_NON_FIELD_ERROR';
export const FORM_OBJECT = 'FORM_OBJECT';
export const FORM_SUCCESS = 'FORM_SUCCESS';
export const FORM_VALIDATION = 'FORM_VALIDATION';

export const HARDWARE_COMPANY_DOMAIN_ALLOWED = 'HARDWARE_COMPANY_DOMAIN_ALLOWED';
export const HARDWARE_COMPANY_DOMAIN_BASE = 'HARDWARE_COMPANY_DOMAIN_BASE';

export const INSTALL_SUCCESS = 'INSTALL_SUCCESS';
export const INSTALL_VALIDATION = 'INSTALL_VALIDATION';
export const INSTALL_WARNING = 'INSTALL_WARNING';